### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by HalvesChen** [jumpercc/python-pcl-ndt#1]
When I run ``python setup.py install``, there is an error:
```python
running install
running bdist_egg
running egg_info
creating python_pcl_ndt.egg-info
writing requirements to python_pcl_ndt.egg-info/requires.txt
writing python_pcl_ndt.egg-info/PKG-INFO
writing top-level names to python_pcl_ndt.egg-info/top_level.txt
writing dependency_links to python_pcl_ndt.egg-info/dependency_links.txt
writing manifest file 'python_pcl_ndt.egg-info/SOURCES.txt'
error: package directory 'python_pcl_ndt' does not exist
```
How do I solve it? Thanks!

**Comment by jumpercc** [comment]
Hello!
You need an empty directory with that name.
I've added one to this repository.
Try ```git fetch && git pull``` and then build again

**Comment by HalvesChen** [comment]
> Hello! You need an empty directory with that name. I've added one to this repository. Try `git fetch && git pull` and then build again

It works! Thanks for your help:)
